spring:
  application:
    name: campus-competition-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/campus_competition?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
